name: dsenv
channels:
- conda-forge
dependencies:
- pangeo-notebook==2021.02.07
- jupyter-panel-proxy
- xarray
- zarr
- intake
- intake-xarray
- pandas
- hvplot
- panel
- datashader
- fsspec
- s3fs
- cmocean